<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ESFE_Tienda.de_ropa.DAL\ESFE_Tienda.de_ropa.DAL.csproj" />
    <ProjectReference Include="..\ESFE_Tienda.de_ropa.EN\ESFE_Tienda.de_ropa.EN.csproj" />
  </ItemGroup>

</Project>
